### ISSUE TITLE
Segmentation Fault on building and running Sandbox from newly cloned repository

### ISSUE THREAD

**Issue by dropTableUsers42** [inanevin/LinaEngine#55]
On a fresh clone of the repository, the following code throws a segfault:

In function `OpenGLRenderEngine::RenderModelPreview (OpenGLRenderEngine.cpp:744)`:

    m_modelNodeSystem.FlushModelNode(model->m_rootNode, modelMatrix, m_defaultDrawParams, overrideMaterial);

Because `model` is NULL

**Comment by inanevin** [comment]
There was a file sync problem between master and dev branch (upper-case & lower-case conflict, unfortunately git didn't catch the changes), now this should be fixed.
