### ISSUE TITLE
Reduce the use of macros

### ISSUE THREAD

**Issue by C-BJ** [inanevin/LinaEngine#77]
Macros really reduces the readability of the program. I will also work on this issue

Compilation errors in release mode, which take me so long to debug because of abusive macros

Related discussion: https://github.com/inanevin/LinaEngine/discussions/65

**Comment by C-BJ** [comment]
Related discussion: https://github.com/inanevin/LinaEngine/discussions/65

**Comment by inanevin** [comment]
Closed for further talk in the discussions.
